### ISSUE TITLE
Fedora 25 installation

### ISSUE THREAD

**Issue by Fenwick17** [openrazer/openrazer#105]
Having some issues with the Fedora installation setup on my PC, as im hoping to stop my blackwidow doing the full rainbow.
When i run make I get http://pastebin.com/6Mg34kXC

**Comment by terricain** [comment]
run `make driver_verbose`

**Comment by z3ntu** [comment]
I just tried a fresh Fedora 25 virtual machine and got the same problem:

## Get the kernel driver to work
```
[luca@localhost razer-drivers]$ make driver_verbose

:: Compiling Razer kernel modules
========================================
make -C /lib/modules/4.8.11-300.fc25.x86_64/build SUBDIRS=/home/luca/razer-drivers/driver modules
make[1]: *** /lib/modules/4.8.11-300.fc25.x86_64/build: No such file or directory.  Stop.
Makefile:28: recipe for target 'driver_verbose' failed
make: *** [driver_verbose] Error 2
[luca@localhost razer-drivers]$ ls -al /lib/modules/4.8.11-300.fc25.x86_64/build
lrwxrwxrwx. 1 root root 39 Nov 28 19:47 /lib/modules/4.8.11-300.fc25.x86_64/build -> /usr/src/kernels/4.8.11-300.fc25.x86_64
[luca@localhost razer-drivers]$ ls -al /usr/src/kernels/4.8.11-300.fc25.x86_64
ls: cannot access '/usr/src/kernels/4.8.11-300.fc25.x86_64': No such file or directory
```
But I fixed it by running `sudo dnf install kernel-devel`, then the directory `/usr/src/kernels/4.8.11-300.fc25.x86_64` is populated with files and the compilation works fine.

Then install everything by using `sudo make -s all install`

The kernel module loads nicely and the device binding is flawless ;)

## Get the daemon to work
`sudo dnf install python3-setproctitle` for at least getting razer-service to start (not working yet ~~because of a screensaver issue at https://github.com/terrycain/razer-drivers/blob/master/daemon/razer_daemon/misc/screensaver_thread.py#L123~~ still not working after working around that)

`sudo pip3 install notify2` (where's the fedora package?!)

Add yourself to the `plugdev` group:
```
sudo groupadd --system plugdev
sudo gpasswd -a luca plugdev
```

## Get the python library to work
`sudo dnf install python3-numpy`

*I am updating this comment as I am figuring out stuff*

**Comment by terricain** [comment]
can you get to the point of modprobe razerkbd?

**Comment by z3ntu** [comment]
Duplicate of #86
