### ISSUE TITLE
Can not open polychromatic controller

### ISSUE THREAD

**Issue by Bryan9995** [openrazer/openrazer#1200]
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I can still use the daemon, and change the colors. but the controller doesn't seem to want to launch since the new mint update. I had an issue previously where i had to change the text in a python file (I can't remember which one).

I made a new issue report because it seems like no one else has this issue.

Thanks!

**Comment by chabad360** [comment]
This appears to be an issue with [Polycromatic](https://github.com/polychromatic/polychromatic) not OpenRazer. Please close this issue and open one [there](https://github.com/polychromatic/polychromatic/issues).

**Comment by lah7** [comment]
It's due to Python 3.8. Be sure to reinstall the `polychromatic` package for Ubuntu 20.04 (Linux Mint 20 is based on)

Upgrading from LM 19 will have disabled the PPA. Open **Software Sources**, re-enable under the **PPAs** tab, refresh the Apt cache, and then check for updates again.

If no updates appear after re-enabling the PPA:

    sudo apt install --reinstall polychromatic

https://github.com/polychromatic/polychromatic/issues/245#issuecomment-632052615
