### ISSUE TITLE
Making a Slackware package question

### ISSUE THREAD

**Issue by mdinslage** [openrazer/openrazer#1243]
Hi all, now that 2.8.0 supports Basilisk mouse, I went ahead and made a Slackware package for openrazer, I plan on submitting it to www.slackbuilds.org when version 15 goes stable.  I have one question though...

During the build process, once the kernel modules are built, I move them from /usr/src/openrazer to /lib/modules/VERSION/kernel/drivers/hid which is the correct location for Slackware.   After that can I safely delete the /usr/src/openrazer directory or are there other files in there that are needed?  I am thinking it can safely be deleted after the modules are build and moved or copied out?

**Comment by z3ntu** [comment]
Hi, that depends on whether you want the package to contain the built kernel modules or if you'll ship the sources which will be built with dkms. In the former case you just need the *.ko files and in the latter just the sources in /usr/src . Afaik just Solus has binary packages for the kernel modules, the rest of the distros is handled via dkms because I can't guarantee a timely rebuild for every kernel update that's coming down in the distro. So basically it depends what your distro is doing in other packages.

**Comment by mdinslage** [comment]
Slackware will just need the modules then, its standard practice to build and include modules in your SlackBuild.  Yeah the package will need to be rebuilt every time there is a kernel update, but that is not very often in the stable Slackware branch, only if there's a vulnerability.   Plus the Slackware community will already know this.  Many Slackware packages are like this,  the NVIDIA kernel package comes to mind.   

Thanks for this project,  It's nice having my mouse a static color now  :)
