### ISSUE TITLE
Razer Cynosa V2 Volume Buttons

### ISSUE THREAD

**Issue by MCSH** [openrazer/openrazer#1337]
### Distribution

Arch Linux, razer version 2.9.0-1

### Support

- [x] Have you tried rebooting?
- [X] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The volume up and volume down keys work as a down arrow and a left arrow respectively whenever the daemon is running. Killing the daemon fixes the issue, but that's not a real solution.

**Comment by dsypniewski** [comment]
I'm having the same problem, before installation of this driver the keys were working just fine.

**Comment by no95typem** [comment]
Manjaro. I am experiencing the same problem. Fix it please. If you need information from the keyboard, I will be glad to help.

**Comment by no95typem** [comment]
I experimented a little - the problem is that in the driver mode in the event files, the binary code for pressing the Volume + and Right Arrow (and Volume- and Down Arrow) keys are identical. I have not yet fully understood the driver code, and therefore I have a question: does this binary code in the event files depend only on the keyboard or on the driver on the PC too?

**Comment by no95typem** [comment]
This #1385 should fix this issue.

**Comment by MCSH** [comment]
Thank you for solving it, @no95typem; I was planning on hacking away during the holidays, but I'm glad it's resolved (well, once they merge, it will be resolved, but we'll get there!)

**Comment by MCSH** [comment]
Any ideas when is the next release? Debating whether I should switch to git or remain on the previous release build.

**Comment by z3ntu** [comment]
Definitely not very soon, so build the version you need for now.
