### ISSUE TITLE
openrazer-daemon no init

### ISSUE THREAD

**Issue by adrianro9224** [openrazer/openrazer#1373]
### Distribution
Ubuntu 18.04.5 LTS

v2.9.0
### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

The openrazer-daemon no init from the last update.

the result  of openrazer-daemon -Fv is:
![Screenshot from 2020-12-16 17-51-36](https://user-images.githubusercontent.com/9616082/102416518-fb2cef80-3fc7-11eb-83a6-269b093aa197.png)

**Comment by lah7** [comment]
Looks similar to #1354 (and #1351). Some invalid data got written to persistence when the certain effects were selected. This should have been fixed in 604f1cab3a899a1877e787e0e6e42b58c289f3ed.

You can either:

* Delete the file at `~/.config/openrazer/persistence.conf`,  which will reset effects to spectrum. This error would happen again upon choosing ripple and restarting the daemon.
* Edit the file and replace `\x02` with `2`.

Make sure you've got the latest build from master containing the fix:

    sudo add-apt-repository ppa:openrazer/daily
    sudo apt upgrade openrazer-meta openrazer-daemon

**Comment by adrianro9224** [comment]
Thanks guys the option: Delete the file at ~/.config/openrazer/persistence.conf works for me.
