### ISSUE TITLE
Support for Kraken X for console

### ISSUE THREAD

**Issue by Aslemammad** [openrazer/openrazer#1396]
### Device Info

* Name: Razer kraken X for console
* Product Number: <See under device>
* Model Number: RZ04-0289

**Comment by z3ntu** [comment]
Please provide the output of `lsusb | grep 1532`

**Comment by Aslemammad** [comment]
@z3ntu  nothing

**Comment by z3ntu** [comment]
It seems the device only has a 3.5mm headphone jack, and no lighting so nothing we can control with openrazer. Please correct me if I'm wrong.

**Comment by Aslemammad** [comment]
@z3ntu  I wanted to access the 7.1 option.

**Comment by TermoZour** [comment]
Are you talking about surround audio? If so, check this link out. It works for any headphones. Since you're not bound to Razer's audio driver and you can do whatever you want on Linux, make your own virtual surround. 

https://forum.endeavouros.com/t/howto-setting-up-virtual-surround-sound-for-headphones/6889
