### ISSUE TITLE
I keep getting a failed to fetch error

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#1452]
Failed to fetch http://ppa.launchpad.net/openrazer/daily/ubuntu/pool/main/o/openrazer/openrazer-driver-dkms_2.9.0-1~610~ubuntu20.10.1_all.deb  404  Not Found

-I will make the note that I had open razer before, but it stopped working so I tried reinstalling, but then I couldn't install it again

**Comment by z3ntu** [comment]
You might need to run `sudo apt update` and then try again.

**Comment by ghost** [comment]
> You might need to run `sudo apt update` and then try again.

That was actually the first thing I tried and that did nothing. I then tried cleaning all the open razer files that did make it on the computer and tried again and that didn't work either

**Comment by lah7** [comment]
Make sure there are no other errors when you run `sudo apt update`. Try disabling all third party sources in **Software & Updates → Other Software** tab and re-enable them one at a time.

Some cache might be outdated on your end since [the latest package in the PPA](https://launchpad.net/~openrazer/+archive/ubuntu/daily) is `2.9.0-1~612` (not `610`)

**Comment by ghost** [comment]
> Make sure there are no other errors when you run `sudo apt update`. Try disabling all third party sources in **Software & Updates → Other Software** tab and re-enable them one at a time.
> 
> Some cache might be outdated on your end since [the latest package in the PPA](https://launchpad.net/~openrazer/+archive/ubuntu/daily) is `2.9.0-1~612` (not `610`)

ya somethings not in there I'm just going to say screw it and do a reinstall of pop os
