### ISSUE TITLE
ModuleNotFoundError: No module named 'openrazer_daemon'

### ISSUE THREAD

**Issue by toza-mimoza** [openrazer/openrazer#1527]
### Distribution

Arch Linux - Garuda, latest update 5.12.9-zen1-1-zen

### Support

- [x] Have you tried rebooting? 
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? 

Before installing: updated system and kernel using `sudo pacman -Syu` and `sudo pacman -Syu linux-headers` respectively. 
Installed openrazer successfully as recommended in the doc using: `pacaur -S openrazer-meta`

I have added the current user to the plugdev group as predescribed and then rebooted the system but still the `openrazer-daemon` fails to start/enable and is not found. Running `openrazer-daemon -Fv` gives the following error: 

```
Traceback (most recent call last):
  File "/usr/bin/openrazer-daemon", line 11, in <module>
    from openrazer_daemon.daemon import RazerDaemon, __version__
ModuleNotFoundError: No module named 'openrazer_daemon'
```
Shebang line in this file is: `#!/usr/bin/python3`

Python version is 3.8.5. 

Executing `which python3 ` results in the following path: 
/home/galaktoza/anaconda3/bin/python3

Spare some time for a help? Thanks in advance.

**Comment by lah7** [comment]
> Executing `which python3` results in the following path:
> /home/galaktoza/anaconda3/bin/python3

This is the problem - Anaconda's Python is being used instead of the system's. Presumably you use this virtual environment, so uninstalling `anaconda` (AUR?) and/or deleting that directory might not be an option.

Have you manually set a `PATH` or `PYTHONPATH` anywhere? Check the files `/etc/environment`, `~/.bashrc`, `~/.bash_profile` and `~/.bash_aliases`. If it's there, remove/comment it out, log out and log back in and the desktop environment should be back to using the system's. Other Python-based programs may also fail to start.

Another way to get it running temporarily is to explicitly set the paths beforehand:

```bash
export PYTHONPATH=/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/lib/python3.9/site-packages
export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
openrazer-daemon -Fv
```

(These are used for Arch at the moment)

**Comment by toza-mimoza** [comment]
So I completely uninstalled Anaconda and the `which python` command now shows: `/usr/bin/python`, a system-wide Python path. Also reinstalled with pacaur the openreazer-meta package. Despite that, the error persists. There is no difference in output between `openrazer-daemon` and `openrazer-daemon -Fv` .

Edit: 
Forgot to mention that the Python version is now 3.9.5.

**Comment by lah7** [comment]
`openrazer-meta` is just a meta package depending on the other packages - try reinstalling these packages:

    openrazer-daemon python-openrazer

Hopefully it'll work after that, since the package will be rebuilt under the correct system paths. 🤞🏼

**Comment by toza-mimoza** [comment]
That fixed it. Thanks.
