### ISSUE TITLE
Support for Breathing Logo on newer Razer Blades

### ISSUE THREAD

**Issue by j-maynard** [openrazer/openrazer#1574]
The newer Razer Blades support a breathing logo effect.  Currently OpenRazer only supports On/Off for the logo.  Raising this issue to track support for this feature.  Below is a screen shot from the lighting options for the Blade Advamce Mid 2021 4k Model.

![image](https://user-images.githubusercontent.com/29251905/128413970-e680a2aa-4784-4cad-a20b-276fcae905b1.png)

**Comment by z3ntu** [comment]
Please provide USB packet captures. If possible turn off all rgb lighting except for the logo one when doing that.

**Comment by j-maynard** [comment]
Attached is a pcap for the breathing logo on the Mid-2021 Razer Blade Advanced.  This pcap follows the following actions:
* Off -> Static
* Static -> Off
* Off -> Breathing
* Breathing -> Off

I've included the off to static and back again as reference points.  This should help with identifying what's going on with the breathing logo.  From my own observations so far its not done in software but actually done with a single request rather than keep updating the brightness of the logo in software.

[blade-advanced-mid-2021-breathing.zip](https://github.com/openrazer/openrazer/files/7320509/blade-advanced-mid-2021-breathing.zip)

**Comment by j-maynard** [comment]
@z3ntu Can you confirm that the pcap makes sense and if it does remove the "need pcap" flag from this?  I am going to work on trying to decode the pcap myself later and see if I can implement the breathing logo on my own as soon as I have sometime towards the end of the week maybe.

Probably worth adding if I have captured the pcap right I'll be able to do the same with Firewire/USB-4 Dock at the end of this week which means I can hopefully progress that as well.

**Comment by z3ntu** [comment]
Looks good, the device uses `razer_chroma_standard_set_led_effect(VARSTORE, LOGO_LED, ...)` and `razer_chroma_standard_set_led_state(VARSTORE, LOGO_LED, ...);` so nothing special really.

**Comment by brian-mcnamara** [comment]
Just to chime in here, it looks like this was prevented in #423 as an undocumented feature. Based on the comments, its simply a tri-state (0,1,2) value.

Edit: Spent some time digging into a pcap and playing around with it, it seems the tristate is interesting... the `razer_chroma_standard_set_led_effect` sets the breathing effect where the value can either be 0 or 2. `razer_chroma_standard_set_led_state` on the other hand is used for whether the logo is on or off.

So the truth table looks something like

|            |  effect(0)  |  effect(2)    |
| -------- | ------------- | -------------- |
| state(0) |  Off    |  Breathing    | 
| state(1) |   On   |  Breathing   |  

It will be easy to add an extra control file and methods, but polychromatic will need some changes to make two calls to determine the state of the device.

I also am unsure what all devices support this. It sounds like modern laptops do, but do any keyboards? Do older laptops support this?

Edit 2: Spend time trying to implement this from the kernel to the daemon to polychromatic and I am starting to think I may be missing something because on the UI side things get ugly. https://github.com/openrazer/openrazer/compare/master...brian-mcnamara:breath?expand=1 for the current work on openrazer and https://github.com/polychromatic/polychromatic/compare/master...brian-mcnamara:breath?expand=1 for polychromatic.
