### ISSUE TITLE
Razer Effects question: How to apply custom effects on opening game.

### ISSUE THREAD

**Issue by Mayravixx** [openrazer/openrazer#1603]
### Distribution 

Manjaro
Kernel version: 5.14.2-arch1-2

### Support

- [x] Have you tried rebooting? yes
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page? yes

Just wondering if anyone knows at all how I could apply a specific custom effect to a game I play in Wine, specifically Friday Night Funkin'. I remember with Synapse, it often had custom colors depending on game, for example custom colors for certain keys for Euro Truck Simulator 2, and I was wondering if I could get Polychromatic/OpenRazer to apply these effects automatically when I open the executable I want to set for them.

**Comment by lah7** [comment]
For Steam/Proton games, you could create a "wrapper" script and modify the launch options (right click → properties). Since you're using Polychromatic, there is a CLI interface to set the effect.

Create the script:
```bash
#!/bin/bash
polychromatic-cli -e "$1"
shift 1
exec "$@"

```

Then for the launch options:

    /path/to/script.sh "Name of Effect" %command%

The same can be done for anything, by changing the _executable_ line for the launcher, if there's no "run before launching" option.

---

Otherwise, I'd say this would be a feature better suited for frontends, scripts or third party projects to implement.  This is something I'd like to do in Polychromatic, but it'll be quite some time before I get to working on that feature. I haven't devised any code on how to do this efficiently neither. It would make a nice [a example script](https://github.com/openrazer/openrazer/tree/master/examples) to demonstrate the use case.

You'll just need a way to _watch_ the process list (`/proc/*`) or _poll_ until the process name has a PID, and then run a command that sets the effect.

This is a pretty crude bash script that would wait for a single application - in this case `nano`:
```bash
#!/bin/bash
while ! pidof nano
do
    sleep 1
done
polychromatic-cli -e "Nano"

# More code is needed to wait until the process exits or start again.
```

🔋 ☠️  "Polling" every second like this probably isn't efficient for laptops with batteries.

Also, for users with other (or no) frontends, a custom effect could be written as a Python script and launched that way. See the [examples](https://github.com/openrazer/openrazer/tree/master/examples).

**Comment by z3ntu** [comment]
Closing as the question is now answered.
