### ISSUE TITLE
Add support for Razer Blade Pro (2017)

### ISSUE THREAD

**Issue by jbagel2** [openrazer/openrazer#264]
Have had the new blade pro for about a week. Working on getting a daemon working for it. so far no luck. Willing to provide any info necessary. 

Running a non standard Debian fork (Kali) .

Will update with new info or submit pull request if find work around.

Razer Blade Pro (2017) - 1532:0225

**Comment by ch4p** [comment]
Hello, here also running Kali rolling 2017.1 no luck on detecting any devices. daemon runs but fails to show any devices to polychromatic.

**Comment by hpyl** [comment]
Update: I managed to bind the driver and I am able to change colours etc. on keyboard manually through /sys

**Comment by z3ntu** [comment]
* Please post the output of
`lsusb -d 1532:0225 -v`
and
`ls -lah /dev/input/by-id/`
* Read [this](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
* Screenshots of all available options on Razer Synapse are needed.
* And lastly, the product & model number of the device for documentation reasons please.

**Comment by terricain** [comment]
Yeah `0225` isnt supported yet. Screenshots of synapse before the packet captures would be more useful as I can make educated guesses from that (which are then confirmed by packet captures)

**Comment by jbagel2** [comment]
First the requested command output. 

[razer_blade_pro_2017_lsusb.txt](https://github.com/terrycain/razer-drivers/files/968150/razer_blade_pro_2017_lsusb.txt)
[razer_blade_pro_2017_dev_by-id.txt](https://github.com/terrycain/razer-drivers/files/968155/razer_blade_pro_2017_dev_by-id.txt)

**Comment by terricain** [comment]
Awesome

**Comment by jbagel2** [comment]
What synapse screenshots are you looking for? I have a Windows vm set up. But I only get one attempts per vm install.. as after the synapse install if I reboot the vm it the guest just bluescreens. But prior to reboot. Synapse works great.

**Comment by z3ntu** [comment]
Just go through every tab in Synapse and make a screenshot of that.

**Comment by jbagel2** [comment]
sorry for the long delay in response, how do you want me to get you the screenshots?

**Comment by minecrawler** [comment]
doesn't matter. Just upload them somewhere. I used imgur for my screenshot scripts, so that's one option. You can also upload them to dropbox. Just make sure people can access and view them.

**Comment by KazWolfe** [comment]
For what it's worth, I got (at least some) of the features working on the 2017 Blade Pro by just reusing the code from the older Blade Pro (0210). 

[Here is the diff](https://github.com/openrazer/openrazer/files/1371037/diff.txt) for my changes. Just a simple substitution.

I can control lighting effects directly through the `/sys/bus/hid/drivers/razerkbd` interface, so that's something. All effects seem to work, but I didn't test too thoroughly. Ripple does appear to be broken, sadly.

~~Polychromatic doesn't seem to detect the device, but I guess that could be due to any number of reasons.~~ Plugdev was being annoying. Got it responding now, looks like this is all that was necessary.

If this alias is all that's necessary (I seem to think so right now), I can throw together a quick (formal) pull-request with the 2017 version added as its own thing.

**Comment by KazWolfe** [comment]
Pushed a PR as seen above (sorry for the mess, Git is dumb).

I did test lighting locally, and it all appeared to work decently well, with the exception of ripples which currently appear to be broken.

If possible, I would like to get confirmation from others that this driver version actually works for them too.
