### ISSUE TITLE
Why this driver is not part of Kernel ?

### ISSUE THREAD

**Issue by ikus060** [openrazer/openrazer#270]
Any reason why this driver is not part of the official Linux Kernel ?

**Comment by z3ntu** [comment]
See #29 probably

**Comment by terricain** [comment]
Currently driver still changes a bit too much anyway so having it in mainline kernel would restrict that more than I would like.

**Comment by z3ntu** [comment]
And also new device support would take forever to land in some distros (eg Debian/CentOS (yes, people tried to use the driver on CentOS) or Ubuntu LTS).

**Comment by madscientist42** [comment]
Yep.  It REALLY should be a userspace beastie...  Under Windows...they
don't bolt it on that way and since there's loads of hook ability to make
it work where it needs.to...I'd chimed in ages ago with a bit on Insight
back when GKH spoke up.  I just got mired down with the thing called 'life'
and didn't get done on my end of things.  About to change.  Look in the
linked thread for more...
