### ISSUE TITLE
gnome-shell issues

### ISSUE THREAD

**Issue by borgdylan** [openrazer/openrazer#282]
I recently switched to gnome-shell ahead of unity's impending doom. When I lock my screen, the keyboard turns all leds off. When I am logging in I have to turn the backlight on manually. If I do that, it turns off by itself on successful log in. If I do not turn it on myself, it turns on log in. Is there something that can be done (apart from keeping on resorting to the fn+f12 hack)?

**Comment by z3ntu** [comment]
It's a feature, that the backlight turns off when the screensaver is active. Unfortunately we are not aware of any D-Bus events that signal the actual monitor sleep and wakeup so we are using the screensaver events that are supported by all major desktop environments (i.e. screensaver lock and screensaver unlock => `org.freedesktop.ScreenSaver`).

If you know a solution how we can do it better, please feel free to let us know. Closing for now because it's working as intended. 🙂

**Comment by borgdylan** [comment]
It seems that you are executing a flag toggle. For unlock it should be a turning on (setting to 100% or last non 0% value if that is tracked) of the backlight rather than toggle. Like that it will not turn off if I turned it on manually.

**Comment by borgdylan** [comment]
also gnome implements a WakeupScreen event on org.gnome.Screensaver but I'm sure its non-standard

**Comment by terricain** [comment]
No the screensaver DBus handler is acting upon the state value passed when an activeChanged event is emitted. I cant reproduce the issue but I too will soon need to move to gnome shell so it'll probably appear soon.

**Comment by borgdylan** [comment]
Most of the issues actually arise from the move to gdm3 from lightdm. That move is mandatory when moving to gnome-shell if you want your lock screen and locking in general to work.

**Comment by terricain** [comment]
Is a shame, never had any issues with lightdm

**Comment by borgdylan** [comment]
Lightdm has been the center of a CVE recently.

**Comment by terricain** [comment]
Ha, but then again its the same with anything. You look hard enough and your bound to find something.
