### ISSUE TITLE
razer lancehead support please!

### ISSUE THREAD

**Issue by emzenrecords** [openrazer/openrazer#373]
please make razer lancehead support

**Comment by terricain** [comment]
Please post the output of
`lsusb -d 1532:003e -v`
and
`ls -lah /dev/input/by-id/`
Read [this](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol) because we probably need packet captures.
Screenshots of all available options on Razer Synapse are needed.
And lastly, the product & model number of the device for documentation reasons please.

**Comment by garrappachc** [comment]
@terrycain this is already done https://github.com/terrycain/razer-drivers/issues/322

**Comment by terricain** [comment]
ahh good point
