### ISSUE TITLE
daemon not starting

### ISSUE THREAD

**Issue by BlazeKl** [openrazer/openrazer#454]
I can't get the daemon to start, I tried updating, recompiling(from branch "feature_abyssus1800"), reinstalling and rebooting. I get the following error:
`Traceback (most recent call last):`
`  File "/usr/bin/openrazer-daemon", line 168, in <module>`
`    run()`
`  File "/usr/bin/openrazer-daemon", line 163, in run`
`    logger=logger)`
`TypeError: __init__() got an unexpected keyword argument 'foreground'`

sometimes the word "foreground" changes to "chdir", using ubuntu gnome 17.04

**Comment by z3ntu** [comment]
I think you are using an old version of python3-daemonize. Could you please try installing python3-daemonize from the PPA and trying again?

**Comment by BlazeKl** [comment]
I updated from daily ppa and now it's working, also the abyssus 1800 support works pretty well on polychromatic, thanks.

**Comment by z3ntu** [comment]
Great 🙂

**Comment by Ayak973** [comment]
Hello, just for your information, with Debian (4.9.0-4-amd64 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64) on a Macbook Pro 17" mid 2011, the Opensuse repo didn't work even following the tutorial, I had the same error ([...] unexpected keyword argument 'foreground').
I'd have to install python3-daemonize version 2.4.7-1 from the official Debian Sid repository, then install openrazer-meta directly from the Ubuntu xenial repo.
Regards

**Comment by z3ntu** [comment]
@Ayak973 You say it didn't work on openSUSE, which version of openSUSE was this?
And can you tell me what steps you took on Debian (again, which version?) when it didn't work?

**Comment by Ayak973** [comment]
@z3ntu : I didn't say that it didn't work on Opensuse, but the installation on Debian from the Opensuse repositories (see after) give me the same error when I start the openrazer daemon :
I have downloaded and installed the Debian Stretch 9.3 from the netinstall media (`'uname -r'` give me `4.9.0-4-amd64 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64`).
I have clicked on the link for Debian provided at https://openrazer.github.io/ wich send me to https://software.opensuse.org/download.html?project=hardware%3Arazer&package=openrazer-meta
I've followed the instructions below `'For Debian 9.0 run the following as root'`, and tried to start the openrazer-daemon. It cannot start, because of the same error reported on this issue.

**Comment by z3ntu** [comment]
I just tested Debian 9.3 in a VM and everything works as expected. 
![image](https://user-images.githubusercontent.com/3768500/36353882-8b40efa6-14cc-11e8-9575-6c72d89d6d5c.png)

**Comment by Ayak973** [comment]
Well, the kernel version of my installation differs from yours (4.9.0-5, 2018-01-04 vs 4.9.0-4, 2017-12-23) maybe a recent update has fixed the issue.
Sorry for the inconvenience...

**Comment by z3ntu** [comment]
The problem described in the first comment of this issue has nothing to do with the kernel. Well if it works now, it's good.
