### ISSUE TITLE
Can't control speed for wave effect in Razer Firefly

### ISSUE THREAD

**Issue by denisse-dev** [openrazer/openrazer#496]
I can control the brightness and direction of the effect but not the speed of the effect.

The speed is too fast and does not allow to fully appreciate the effect, is there a way to control the speed?

I'm using the latest version from the AUR.

**Comment by z3ntu** [comment]
Which frontend are you using? I think this should be an issue in the repository of that frontend.

**Comment by denisse-dev** [comment]
polychromatic, but the same happens with razergenie and razercommander.

**Comment by lezed1** [comment]
@da-edra can you control the speed in Windows? I don't remember that option personally, but I may be wrong.

**Comment by denisse-dev** [comment]
I don't use Windows but yes, you can do that there with the Chroma configurator.

**Comment by z3ntu** [comment]
Yes, the daemon doesn't support a speed argument for setWave. If you can find us a screenshot (Google or similar) from Synapse where it's possible we can talk about it. But as wave is a hardware effect, synapse also has to have the effect.

**Comment by denisse-dev** [comment]
I see... I think I confussed it with Corsair Polaris where you can adjust the speed.
Thank you.

**Comment by zkarcher** [comment]
@lezed1 @da-edra On the Razer Blade 15 2018, the speed can be controlled in Windows. (Screenshot attached.) Is there any chance this issue can be re-opened?

![Windows_wave_speed](https://user-images.githubusercontent.com/177089/54729377-6bcb8180-4b40-11e9-9231-93c3b55c60b4.png)

**Comment by lezed1** [comment]
@zkarcher That looks like the custom effect gui which calculates all the color values in software and then sends the colors many times pet second to the keyboard. This is different from telling the keyboard once to play a standard wave effect, and not needing to send each frame of the animation. The hardware effect is not as configurable.

The daemon's setWave controls the hardware effect. If you want more control, you can calculate colors in software and use the daemon to send each frame several times a second.

The daemon itself doesn't support these complex effects, but all hope is not lost! I have some examples in this repo regarding how to use the advanced Python API. I also have 2 separate libraries designed to easily run complex effects over time. If you are interested in writing your own effects, I'm happy to help since that is my personal favorite use of OpenRazer.

**Comment by zkarcher** [comment]
@lezed1 Thanks for explaining this!

I just wrote code using the Python API, and I was able to produce the exact effect I wanted in software. Gist: https://gist.github.com/zkarcher/b27493baf3a026d6b9dce9069eb4ceec

I'd like to check out your libraries for running complex effects, do you mind sharing the repos?

**Comment by lezed1** [comment]
The better of the two is this project: https://github.com/lezed1/color-full. I don't have any info about how to use it, so feel free to ask me questions. It's split into Effects (complex effects like you want) and Devices (backends to display the effects - a software visualizer is in progress). It's still in a hacky stage, but I have been able to run everything. I'm also happy to merge in things if you modify it. Hopefully it's useful for you to use!
