### ISSUE TITLE
Ripple effect doesn't work on keyboard plugged in after starting the deamon

### ISSUE THREAD

**Issue by GiantBlargg** [openrazer/openrazer#501]
When I plug in my keyboard after starting the deamon, ripple doesn't work, the lights on my keyboard are all off. Restarting the deamon with `systemctl --user restart openrazer-daemon` with the keyboard plugged in fixes the problem, but if I unplug and replug, it is a problem again. Reactive and all other effects work fine.

**Comment by lah7** [comment]
It's due to the fact ripple is a **software effect** and the daemon must be running in order for it to play. Sadly, it's not currently persistent between sessions or hardware changes, i.e. if the keyboard is disconnected or the daemon starts again, then the effect won't start playing again until you trigger that effect again.

In the meantime, if this happens when you login and the keyboard is your only Razer device, you could run this command for the **random ripple**:

    python3 -c "import openrazer.client;a=openrazer.client.DeviceManager();a.devices[0].fx.ripple_random()"

**Comment by z3ntu** [comment]
Fixed in #516
