### ISSUE TITLE
Create a issue template for driver support requests 

### ISSUE THREAD

**Issue by henryruhs** [openrazer/openrazer#547]
May I suggest to introduce a [issue template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) for driver support request?

It seems that many driver support requests are stucked - I would close issues with no response after couple of months - you can also automate this using [probot/stale](https://github.com/probot/stale).

Let me know, if I can give you a helpful hand.

**Comment by z3ntu** [comment]
We have the stalebot configured (see https://github.com/openrazer/openrazer/issues?utf8=%E2%9C%93&q=label%3Awontfix+) but I've excluded device support on purpose as the devices are still not supported even if the creator doesn't answer anymore. I think this is better than closing old ones because nobody responds and waiting for people to create a new one for the same device.

Yes, issue templates would be nice probably but it might be beneficial to have them implemented like this: https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/
