### ISSUE TITLE
Ubuntu 14.04 support

### ISSUE THREAD

**Issue by linuxwwarrior** [openrazer/openrazer#550]
Now, I know that Ubuntu 14.04 does not have some of the versions of dependencies for the files needed to use openrazer or polychromatic, however, does anyone have a solution that would allow me to use Ubuntu 14.04, because I have other hardware that will not work with Ubuntu 16.04 and do not want to upgrade just so I can configure my Razer Ornata keyboard and then have several other pieces of hardware to stop working.

Please advise how I can get this to work on my version of Ubuntu.

Thanks!!

**Comment by z3ntu** [comment]
First of all, you have about a year to upgrade because 14.04 will be EOL then.
Secondly, sure, try installing the 16.04 Deb packages and try to start `openrazer-daemon -Fv` from the console. You'll probably get some errors where you need to install a newer version of some python dependency. Also you might need to upgrade python itself but I'm not sure on that.

**Comment by linuxwwarrior** [comment]
ok, I will try that, thanks and know time is almost running out on 14.04, but trying to hold out to is as long as I can due to some other hardware I have that will not work currently in 16.04

**Comment by z3ntu** [comment]
I will close this issue but feel free to still ask questions or whatever you need!
