### ISSUE TITLE
Remove code that resets mouse brightness and LEDs on startup

### ISSUE THREAD

**Issue by tmitzka** [openrazer/openrazer#644]
Whenever I adjust brightness and LEDs on my Razer Abyssus v2 mouse, they are reset on startup. I actually opened [an issue](https://github.com/openrazer/openrazer/issues/526) for that problem earlier this year. [These code lines](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/hardware/mouse.py#L821-L824) do that. Thanks again to @z3ntu for pointing me in the right direction.

When I comment these lines out, the problem is solved - for now. But with each update, I have to do it again. I don't really understand the code, so I wondered if there's a chance to just remove that part? Or is there a reason to reset the lights on startup?

**Comment by sata1000000** [comment]
Same problem still persists over 4 years later. Would be nice if the devs finally got around to this

**Comment by z3ntu** [comment]
@sq1000000 I believe PR #1957 should solve this, if you could test it that'd be helpful.

**Comment by sata1000000** [comment]
@z3ntu That branch seems to have solved the issue. The keyboard brightness on my Razer Blade 15 (RZ09-0409) no longer resets to 0 after logging in from reboot or suspend.

For whatever reason, polychromatic doesn't see a backend anymore. RazerGenie works fine though. I think that might just be because openrazer it isn't installed as an Arch package anymore.
