### ISSUE TITLE
were is the driver

### ISSUE THREAD

**Issue by nonetrix** [openrazer/openrazer#757]
distro pop os
issue can't find the driver 
spcs fx 8350 gtx 1080 16 gbs of ram

**Comment by tildearrow** [comment]
1. Is it that you can't find a driver for Pop!_OS?
- If so, follow [the Ubuntu instructions](https://openrazer.github.io/#ubuntu) since Pop! is a derivative of Ubuntu.

2. Is it that you installed the driver, but it does not work?
- If so then follow this [issue template](https://github.com/openrazer/openrazer/issues/new?template=support.md) (especially the Support section).

**Comment by z3ntu** [comment]
I'm going to close this issue because there wasn't been a response for over 30 days. Feel free to reply if you are still experiencing this issue.
