### ISSUE TITLE
Running the "ubuntu_install" make target can break your Ubuntu install

### ISSUE THREAD

**Issue by mmarsalko** [openrazer/openrazer#923]
The line:
`mv $(DESTDIR)/usr/lib/python3.* $(DESTDIR)/usr/lib/python3`
in the Makefile causes some serious problems in Ubuntu 18.04. Several applications (including very important basics, like gedit and gnome-terminal) won't start at all when the python3 folders are moved around like this. Is there any particular reason it does this, and doesn't instead symlink the paths?

**Comment by z3ntu** [comment]
The Makefile is supposed to be only used by packaging scripts and is not meant to be run manually. The procedure is necessary during packaging because Python normally installs its files into e.g. `/usr/lib/python3.7/site-packages` but Debian+derivatives expect the files to be in `/usr/lib/python3/site-packages` so this step is necessary.
