### ISSUE TITLE
Security review (fake keyboard input, mouse clicks)

### ISSUE THREAD

**Issue by ghost** [openrazer/openrazer#931]
Running a daemon that controls part of the keyboard, could be a potential security issue. Maybe this is not something a home user would be interested in, but corporate entities may allow its use if there was a peer or security review of the code.

For example, when I tried to install openrazer-meta on Fedora, the package tried to install various dependencies, including: **xautomation** and **xdotool**. Both tools are used for controlling X via the shell (fake keyboard input, mouse clicks, etc), something ideal when a malicious entity wants to use your system to ghost click on adverts and not something I want on my systems.

Has anyone performed a security review on the source code?

Thank you.

**Comment by z3ntu** [comment]
Hi @robo2bobo,

> Running a daemon that controls part of the keyboard, could be a potential security issue.

That's literally what openrazer is and that's all it does.

> For example, when I tried to install openrazer-meta on Fedora, the package tried to install various dependencies, including: xautomation and xdotool.

The xautomation package includes `xte` which is used for making macros work, which is by definition:
> fake keyboard input, mouse clicks, etc

xdotool isn't used anymore and I'll remove it from the dependency list (code using that was removed in November 2017).

> something ideal when a malicious entity wants to use your system to ghost click on adverts and not something I want on my systems.

If you're worried about something sniffing on your input or injecting key events, you shouldn't use X11 at all because every single process running can get everything and do everything. In contrast Wayland was designed with security in mind and has these issues solved there afaik.

> Has anyone performed a security review on the source code?

Not to my knowledge, but feel free to review the code; more eyes are always good :)
