### ISSUE TITLE
Ouroboros Support

### ISSUE THREAD

**Issue by WhatsCS** [openrazer/openrazer#96]
Here is a zip of all settings for the mouse, if I missed anything please tell me. 
[2016-12.zip](https://github.com/terrycain/razer-drivers/files/628413/2016-12.zip)

**Comment by terricain** [comment]
Ok we will deal with Wireless mode first, so until otherwise keep the mouse unplugged :wink:.
I need packet captures (each bulletpoint a seperate capture). Thoughout use a seperate mouse as not to pollute the capture with rubbish. Also make sure you set up the correct filter as documented [here](https://github.com/terrycain/razer-drivers/wiki/Reverse-Engineering-USB-Protocol#phase-2-setup)

- Start wireshark, then start vm, and open up razer synapse. then stop recording.
- Brightness slider, move to max, half, min, half, max, half, min.
- DPI Min, move it in 1000 increments to max
- Sleep mode idle after, move it from min to max through each increment
- Flash battery indicxator falls below, move from min to max through each increment
- Open synapse and just leave running for 5 mins.

**Comment by WhatsCS** [comment]
This should be everything on that list for WIRED, as stated in Telegram I'll let it charge and see where that leads us.
[USB-Inspection-Oro.zip](https://github.com/terrycain/razer-drivers/files/628527/USB-Inspection-Oro.zip)

EDIT: Added idle logs.
[idle.zip](https://github.com/terrycain/razer-drivers/files/628550/idle.zip)

**Comment by terricain** [comment]
> Start wireshark, then start vm, and open up razer synapse. then stop recording.

did you get this capture?

**Comment by terricain** [comment]
Also what distro you on

**Comment by terricain** [comment]
Also whats the output of `lsusb`

**Comment by WhatsCS** [comment]
1. Pretty sure that's idle.zip
2. Arch Linux
3. not sure I'll have to update when I'm on it.

**Comment by terricain** [comment]
Ok I'll double check idle.zip when I get home

**Comment by WhatsCS** [comment]
```
$ lsusb
Bus 006 Device 004: ID 1532:0032 Razer USA, Ltd 
Bus 006 Device 003: ID 1532:010e Razer USA, Ltd
```

**Comment by terricain** [comment]
What one is ouroboros?

**Comment by z3ntu** [comment]
`1532:010e` is ~~either~~ Razer BlackWidow Classic ~~or Lachesis~~ and `1532:0032` is the Ouroboros ;)

**Comment by terricain** [comment]
Ahh good point it is a BW

**Comment by terricain** [comment]
Idle.zip doesnt contain from startup, (or if it does it doesnt have what im looking for)

**Comment by WhatsCS** [comment]
Should include startup.
[idle.zip](https://github.com/terrycain/razer-drivers/files/694462/idle.zip)

**Comment by terricain** [comment]
YES :) that had exactly what I was looking for. Good job

**Comment by terricain** [comment]
Ok @z3ntu as its arch, can you help him here or via telegram install the driver from branch [feature_ouroboros_0x0032](https://github.com/terrycain/razer-drivers/tree/feature_ouroboros_0x0032)

**Comment by z3ntu** [comment]
You probably will get some dependency issues because some packages needed are only available in the AUR -> install them first (AUR helper or whatever you like)
**Run the following commands:**
```
git clone https://aur.archlinux.org/razer-drivers-git.git
cd razer-drivers-git
curl https://gist.githubusercontent.com/z3ntu/28cb958ce9a778de0975e54c54b77318/raw/9e21f1473b04afb47951f4000c0e01d0f7442779/PKGBUILD.ouroboros -o PKGBUILD
makepkg -sr
sudo pacman -U python-razer-git-*.tar* razer-daemon-git-*.tar* razer-driver-dkms-git-*.tar*
```
You can also reach me on Telegram @z3ntu

**Comment by terricain** [comment]
PPA updated.
