### ISSUE TITLE
Configure scroll speed for DeathAdder Elite mouse

### ISSUE THREAD

**Issue by ddickstein** [openrazer/openrazer#963]
None of the front-ends for openrazer seem to have support for modifying the scroll speed for the DeathAdder Elite mouse. I assume this is a limitation on the features openrazer offers? Is there a way to expose this as a configurable setting?

**Comment by z3ntu** [comment]
Hi,
like key rebinding, modifying the scroll speed isn't in the scope of OpenRazer because it isn't a Razer-device specific "problem". You might be able to modify this value using the `xinput` command but I don't see anything like that for my cheap Logitech mouse I currently have with me.

I've also found this issue thread, maybe this can help you: https://gitlab.freedesktop.org/libinput/libinput/issues/185
